apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
        - name: crm
          image: tchao98/crm-web
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: crm